### PR TITLE
feat: Allow specifying heading_level as a Markdown heading instead

### PR DESCRIPTION
**Pull request by oprypin**
This also refactors the regex to use the `MULTILINE` flag instead of the complex "manual" alternative for detecting newlines.

### CODE REVIEW

**Comment by pawamoy** [comment]
Hehehe, you're quick :wink: 

Sorry for not merging in order :sweat_smile:

**Comment by oprypin** [comment]
There would've been a conflict regardless. I was ready :)

**Comment by oprypin** [comment]
Hold on, I might have detected a buggy interaction with the passed config dict (now ChainMap but doesn't change the situation) here. This is mutating it, which may affect other things.

**Comment by oprypin** [comment]
It is done.

> This actually happened to not cause any problems even with the mutation, but better to be safe.

**Comment by pawamoy** [comment]
Great, thanks, squashing and merging!

**Pull request merged**
