### PR TITLE
Fix lack of isolation of Markdown calls from the top-level Markdown

### LINKED ISSUE #186: Footnote appears in all following objects after the first appearance
Hi, I'm not sure this is related to pytkdocs or mkdocstrings.

**Describe the bug**
If a footnote is added to one of python objects, the footnote will appear in every object after that one in the same documentation page.  

**To Reproduce**
Here is an example to reproduce

```python
# example.py
def C():
    """This is C
    """
    pass

def B():
    """This is B[^1]

    [^1]: This is footnote
    """
    pass

def A():
    """This is A
    """
    pass
````
```
# mkdocs.yml
site_name: Footnote
theme:
  name: "material"
plugins:
  - search
  - mkdocstrings:
      default_handler: python
markdown_extensions:
  - footnotes
```
**Expected behavior**
The footnote is supposed to appear only under function B

**Screenshots**
However, footnote appears under function B and C

[
Screenshot from 2020-12-05 00-30-54
](url)

### LINKED ISSUE #192: Markdown headings can bust to the topmost nav level
I'm actually not entirely sure if it's the case for Python renderer, but in my own renderer I ran into the issue that if the docstring contains a `# Markdown Heading`, it's not adjusted according to the current `heading_level`, so in the nav it'll just appear as a topmost item regardless of what's happening around it.

I'm currently looking into a solution.

### PR DESCRIPTION
**Pull request by oprypin**
Fixes #186
Fixes #192

### CODE REVIEW

**Comment by pawamoy** [comment]
Thanks a lot @oprypin! You're doing great work here :star_struck: 

So, footnotes will now appear only once, but if I understand correctly, one cannot use the same id for different footnotes in different docstrings if one's plan is to render these docstrings in the same page? If yes, I'm OK with that, and we should simply document it!

**Comment by pawamoy** [comment]
Also sorry for force-pushing, this is not good practice.

**Comment by pawamoy** [comment]
One more thing: I don't think it fixes #193, right? For footnotes we can force different IDs, so I guess for tabs one would need to use different titles if they plan on rendering them in the same page?

**Comment by oprypin** [comment]
You are correct in all regards in your comments. Yes, I'm not handling ID collisions.

And actually yes, I'm not sure at all why you force-pushed :D.
Didn't need to rebase here at all.

Do you plan to merge this as a branch, or squash perhaps?

**Comment by oprypin** [comment]
ID collisions are possible to handle by prefixing them, just don't know much hackery that would require.

**Comment by pawamoy** [comment]
I rebased to reword the commits :expressionless: I can be obsessive over little details.
I also didn't want to squash because this PR does several things and so I wanted to keep each commit :slightly_smiling_face: 

> ID collisions are possible to handle by prefixing them, just don't know much hackery that would require.

OK, then let's simply document it for now. I'll add a troubleshooting item, merge, and link to the docs in the related issues. Does it sound good?

**Comment by oprypin** [comment]
> I rebased to reword the commits

Ah I see, didn't catch that. Thanks for the style fix as well.

Yes, all good then, no outstanding comments from me.

**Pull request merged**
