### PR TITLE
feat: Support for reStrcuturedText style

### PR DESCRIPTION
**Pull request by plannigan**
Updates version of `pytkdocs` to allow use of release that supports reStructuredText. Also update documentation.

Addresses #176

### CODE REVIEW

**Comment by pawamoy** [comment]
Hello! Thank you for the PR.

This is not technically a feature so I'll squash and use a `docs` type for the commit.
Could you also revert the pytkdocs version range upgrade in pyproject.toml? I'd like to do that in a separate commit once I'm ready to release mkdocstrings version 0.14.

Thanks again!

**Comment by plannigan** [comment]
I can do that. But just to be clear, I updated the docs to include a reStructuredText snippet. So the documentation will not build successfully until the new version of `pytkdocs` is pulled into the project.

The CI failure seems to be an issue `poetry` decides to use `pytkdocs==0.9.0` instead of the newer version. I'm still trying to figure out why that is happening. It might be a conflict with the allowed ranges for the indirect dependencies.

**Comment by pawamoy** [comment]
> But just to be clear, I updated the docs to include a reStructuredText snippet. So the documentation will not build successfully until the new version of pytkdocs is pulled into the project.

OK sure, not a problem :slightly_smiling_face: 

> The CI failure seems to be an issue poetry decides to use pytkdocs==0.9.0 instead of the newer version. I'm still trying to figure out why that is happening. It might be a conflict with the allowed ranges for the indirect dependencies.

Hmmmm yeah, I wonder how deps would resolve if one of mkdocstrings dev dep is also depending on mkdocstrings :sweat_smile:

**Comment by plannigan** [comment]
Made the change as requested. Also, I believe the linked PR will resolve the issue that showed up in CI for this PR.

Because of the inter-dependencies here, it is OK if this PR hangs out open until you are closer to releasing the new version of this project.

**Pull request merged**
